name: Setup Solana
description: Install Solana CLI safely for CI (no external SSL calls)

runs:
  using: "composite"
  steps:
    - name: Install Solana from GitHub release
      run: |
        SOLANA_VERSION="1.18.26"
        curl -L https://github.com/solana-labs/solana/releases/download/v${SOLANA_VERSION}/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
        tar -xjf solana.tar.bz2
        sudo mv solana-release /opt/solana
        echo "/opt/solana/bin" >> $GITHUB_PATH

        solana --version
        solana-keygen --version
      shell: bash
